add_newline = false
# A minimal left prompt
format = """$directory$character"""
# move the rest of the prompt to the right
right_format = """$all"""

[character]
vicmd_symbol = "[N] >>>"

[directory.substitutions]
'/Users/adrifer/Repos/trackseries/src/Web' = 'ts-web'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)](fg:4)'

[docker_context]
disabled = true

[bun]
disabled = true

[nodejs]
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']